### PR TITLE
fix: show error if module-dir does not exist

### LINKED ISSUE #5182: `ftl dev` does not exit on error due to missing module dir
Steps:
- Rename `examples/go` dir to something else
- Run `ftl dev`

Expected:
- FTL should exit with an error saying that `examples/go` could not be found

What actually happens:
- `ftl dev` seems to hang without exiting or printing the error
- It works correctly if `terminal.LaunchEmbeddedConsole` is skipped in `cmd_dev.go`

### PR DESCRIPTION
**Pull request by wesbillman**
Fixes #5182

I'm not sure if this will have unwanted side effects as it could have weird behaviors with new ftl projects where the folder is empty since it's a newly created project.

### CODE REVIEW

**Review by worstell — APPROVED** [review]

File: cmd/ftl/cmd_dev.go [hunk 1]
```diff
@@ -79,6 +79,22 @@ func (d *devCmd) Run(
 	}
 	os.Setenv("FTL_DEV_DIRS", strings.Join(absDirs, ","))
 
+	// Validate module directories before launching console or starting build engine.
```
Comment (matt2e) [inline cmd/ftl/cmd_dev.go:82]: I don't think this is needed. These cases are already be handled in `main`, though it was broken as of last week (fixed here: https://github.com/block/ftl/pull/5180):
```
ftl: error: [<dirs> ...]: stat /Users/mtoohey/Code/ftl/examples/javafake: no such file or directory
🐚 mtoohey ~/Code/ftl [main] $ ftl dev fakedir          
Usage: ftl dev [<dirs> ...] [flags]
Run "ftl dev --help" for more information.
```
```
ftl: error: [<dirs> ...]: stat /Users/mtoohey/Code/ftl/fakedir: no such file or directory
🐚 mtoohey ~/Code/ftl [main] $ ftl dev Dockerfile
Usage: ftl dev [<dirs> ...] [flags]
Run "ftl dev --help" for more information.

ftl: error: [<dirs> ...]: "/Users/mtoohey/Code/ftl/Dockerfile" exists but is not a directory
```

**Review by matt2e — APPROVED** [review]
Looks good Wes :+1: I was surprised that you also didn't need to change the language plugins (which also use the watcher), but it looks like they never closed the channel before... So that's nice to clean this up!

File: cmd/ftl/cmd_dev.go (hunk 1 above)
Comment (matt2e) [reply cmd/ftl/cmd_dev.go:82]: Back when I create the issue about this was when I fixed it made that PR, but the issue remained because the interactive console code was eating the error for some reason. But that appears to be fixed now... 🤷‍♂️
