### PR TITLE
fix: remove queries.ftl.go if no queries

### LINKED ISSUE #4131: FTL should delete queries.ftl.go if all queries are removed

### PR DESCRIPTION
**Pull request by worstell**
fixes #4131

### CODE REVIEW

File: go-runtime/compile/build.go [hunk 1]
```diff
@@ -635,6 +635,11 @@ func scaffoldBuildTemplateAndTidy(ctx context.Context, config moduleconfig.AbsMo
 			if err := filesTransaction.ModifiedFiles(filepath.Join(config.Dir, ftlQueriesFilename)); err != nil {
 				return fmt.Errorf("failed to mark %s as modified: %w", ftlQueriesFilename, err)
 			}
+		} else if _, err := os.Stat(filepath.Join(config.Dir, ftlQueriesFilename)); err == nil && len(mctx.QueriesCtx.Verbs) == 0 && len(mctx.QueriesCtx.Data) == 0 {
+			os.Remove(filepath.Join(config.Dir, ftlQueriesFilename))
```
Comment (matt2e) [inline go-runtime/compile/build.go:639]: Small error check missing
```suggestion
			if err := os.Remove(filepath.Join(config.Dir, ftlQueriesFilename)); err != nil {
				return fmt.Errorf("failed to delete %s: %w", ftlQueriesFilename, err)
			}
```

**Review by matt2e — COMMENTED** [review]
Nice

File: go-runtime/compile/build.go (hunk 1 above)
Comment (worstell) [reply go-runtime/compile/build.go:639]: oop 🤦‍♀️
