### PR TITLE
fix: build engine collects schemas when not deploying

### LINKED ISSUE #5433: `ftl build` does not result in an up to date schema in the build engine
This functionality seems to have been lost in the DeployCoordinator work.

### PR DESCRIPTION
**Pull request by matt2e**
closes #5433

- Build engine collects module schemas when `Build()` is called.
- Build engine hands deploy coordinator each module schema, rather than a path to the schema

### CODE REVIEW

File: internal/buildengine/engine.go [hunk 1]
```diff
@@ -373,7 +373,25 @@ func (e *Engine) Import(ctx context.Context, realmName string, moduleSch *schema
...
+	schemas := make(chan *schema.Module, e.moduleMetas.Size())
+	if err := e.buildWithCallback(ctx, func(ctx context.Context, module Module, moduleSch *schema.Module, tmpDeployDir string, deployPaths []string) error {
+		schemas <- moduleSch
+		return nil
+	}); err != nil {
+		return errors.WithStack(err)
+	}
+	close(schemas)
+
+	realm := &schema.Realm{
```
Comment (matt2e) [inline internal/buildengine/engine.go:385]: @jvmakine Can you check this realm code? I'm not sure what the engine's schema should be after a build when it comes to external realms...

**Review by alecthomas — APPROVED** [review]

File: internal/buildengine/deploy.go [hunk 2]
```diff
@@ -652,14 +651,24 @@ func (c *DeployCoordinator) terminateModuleDeployment(ctx context.Context, modul
 }
 
 func prepareForDeploy(ctx context.Context, modules map[string]*pendingModule, adminClient AdminClient) (err error) {
+	for _, module := range modules {
```
Comment (matt2e) [inline internal/buildengine/deploy.go:654]: This used to be in `loadProtoSchema`
