### PR TITLE
fix: go version for new go modules

### LINKED ISSUE #4687: go.mod versions can get out of sync resulting in go.work conflicts
A newly created module "types" uses the current Go version, but existing modules do not:

```
🐚 ~/…/examples/go $ grep '^go' */go.mod
cron/go.mod:go 1.23.0
echo/go.mod:go 1.23.0
http/go.mod:go 1.23.0
mysql/go.mod:go 1.23.0
postgres/go.mod:go 1.23.0
pubsub/go.mod:go 1.23.0
time/go.mod:go 1.23.0
types/go.mod:go 1.24.0
```

This results in a conflict in go.work files:

```
error:echo:build: Build failed: echo: compile: could not extract schema: failed to load packages: err: exit status 1: stderr: go: module ../../../.ftl/go/modules/types listed in go.work file requires go >= 1.24.0, but go.work lists go 1.23.0; to update it:
	go work use

info: Modules waiting to build: echo
error:build-engine: Initial build failed: echo: compile: could not extract schema: failed to load packages: err: exit status 1: stderr: go: module ../../../.ftl/go/modules/types listed in go.work file requires go >= 1.24.0, but go.work lists go 1.23.0; to update it:
	go work use
```

### PR DESCRIPTION
**Pull request by wesbillman**
Fixes #4687

### CODE REVIEW

File: go-runtime/goplugin/commands.go [hunk 1]
```diff
@@ -43,6 +45,37 @@ type scaffoldingContext struct {
...
+	for _, entry := range entries {
+		if !entry.IsDir() {
+			continue
+		}
+		goModPath := filepath.Join(projectPath, entry.Name(), "go.mod")
+		data, err := os.ReadFile(goModPath)
+		if err != nil {
+			continue
+		}
+		modFile, err := modfile.Parse(goModPath, data, nil)
```
Comment (alecthomas) [inline go-runtime/goplugin/commands.go:70]: I'm pretty sure we already do this somewhere else, but probably NBD.

**Review by alecthomas — APPROVED** [review]
